aspects:
  aspects:
#      nombre_aspecto1:
#          controller_action: DefaultController:indexAction
#          pre_post: pre
#          service_name: cache.aspect
#          method: metodo1
#          order: 1

      